In [1]:
import numpy as np

#REPLICATE THE METRICES

In [2]:
#1
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
#1 SELECT [[12, 13, 14, 15],[17, 18, 19, 20],[22, 23, 24, 25]] FROM the metrix in #1
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [4]:
#2 grab 20 from mat
mat[3,4]

20

In [8]:
# 3 grab [[2],[7],12]] keeping it in its 2 dimension form

mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [9]:
# 4 grab the last row of mat
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [11]:
#5 Grab the last two rows of mat 2 demension
mat[3:, 0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
#6 Get the sum of all values in mat
np.sum(mat)
#or
mat.sum()

325

In [13]:
#7 mat std
mat.std()

7.211102550927978

In [14]:
#8 get the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])